grid_map_visualization:
  ros__parameters:
    grid_map_topic: /grid_map_msgs
    grid_map_visualizations: [elevation_points, elevation_grid]
    elevation_points:
      type: point_cloud
      params:
        layer: elevation
    elevation_grid:
      type: occupancy_grid
      params:
        layer: elevation
        data_min: -0.01
        data_max: 4.68
